[On Hold] Ignore vulnerabilities feature for CLI
fabric8-analytics/cli-tools pull request #79
Opened 2021-11-18 09:50 UTC by AkshayBhansali18

Ignore Vulnerability Feature for Maven, pypi, golang, and npm ecosystems. 
To be kept on hold till Ignore feature is added to the server. 
To be done - change summary statistics to display number of vulnerabilities and packages ignored.

2021-11-30 11:31 UTC, sawood14012 requested changes

2021-11-30 11:31 UTC, sawood14012 commented on pkg/analyses/summary/types.go
> +	TotalTransitiveIgnored		 int
same here

2021-12-02 09:51 UTC, sawood14012 commented
why does package.json has the key ignore but all other ecosystems has crdaignore ?

2021-12-02 10:16 UTC, AkshayBhansali18 commented
> why does package.json has the key ignore but all other ecosystems has crdaignore ?

@sawood14012 because a json file doesn't allow comments, but comments are allowed in manifests of other ecosystems.

2021-12-02 10:18 UTC, sawood14012 commented
> > why does package.json has the key ignore but all other ecosystems has crdaignore ?
> 
> @sawood14012 because a json file doesn't allow comments, but comments are allowed in manifests of other ecosystems.

no i was just taking about the key of the json object

2021-12-02 10:21 UTC, AkshayBhansali18 commented
> > > why does package.json has the key ignore but all other ecosystems has crdaignore ?
> > 
> > 
> > @sawood14012 because a json file doesn't allow comments, but comments are allowed in manifests of other ecosystems.
> 
> no i was just taking about the key of the json object

Ohh, thats because the json sent to the server is sent with key ignore. It could be changed to crdaignore too.

2021-12-02 11:13 UTC, sawood14012 commented
> > > > why does package.json has the key ignore but all other ecosystems has crdaignore ?
> > > 
> > > 
> > > @sawood14012 because a json file doesn't allow comments, but comments are allowed in manifests of other ecosystems.
> > 
> > 
> > no i was just taking about the key of the json object
> 
> Ohh, thats because the json sent to the server is sent with key ignore. It could be changed to crdaignore too.

yup please do

2021-12-07 07:08 UTC, sawood14012 approved these changes
LGTM

2021-12-07 09:18 UTC, merged